# These are supported funding model platforms

github: [isa56]
custom: ["https://www.paypal.com/donate/?hosted_button_id=Y9DZ3PC2JUJUU"]

github: [nikkifurls]
patreon: nicolefurlan
custom: ["https://nicolefurlan.com", "https://www.paypal.com/donate?hosted_button_id=M7MMF3EWQTLKG"]